### PR TITLE
Fix language issue

### LINKED ISSUE #146: Scryfall fuzzy sometimes matches non-English cards
!Flash and put !Nyxbloom Ancient

Steppenbrand {3}{R} · Hexerei · Zerstöre alle Ebenen. · 9ED-U,8ED-U,6ED-U,POR-U,5ED-U,[...] · Vin,Leg,Mod
Nyxbloom Ancient {4}{G}{G}{G} · Enchantment Creature — Elemental · 5/5 · Trample \ If you tap a permanent for mana, it produces three times as much of that mana instead. · THB-M ·

Because "Flash and" matches Flash Fires and Steppendbr _and_

Possible answer:
If card returned isn't in English (and it wasn't a foreign language request), check if the first word of the query is the exact name of a magic card and return that

### PR DESCRIPTION
**Pull request by Villawhatever**
Fixes #146

### CODE REVIEW

File: main_test.go [hunk 1]
```diff
@@ -33,6 +33,11 @@ func fakeGetCard(cardname string) (Card, error) {
 			if err := json.NewDecoder(fi).Decode(&c); err != nil {
 				return c, fmt.Errorf("Something went wrong parsing the card: %s", err)
 			}
+			fmt.Printf("In FakeGetCard: %v %v\n", c.Name, c.Lang)
+			if (c.Lang != "en" && !isLang) {
+
```
Comment (Fryyyyy) [inline main_test.go:38]: Superfluous blank line

**Comment by Fryyyyy** [comment]
Nice!

File: main_test.go (hunk 1 above)
Comment (Villawhatever) [reply main_test.go]: Fix't
